### ISSUE TITLE
Python 3.x mixed tabs and spaces

### ISSUE THREAD

**Issue by DrASK** [tbird20d/grabserial#14]
I'm trying to run in Python 3.5.2, but I keep getting this error:

`TabError: inconsistent use of tabs and spaces in indentation`

According to [PEP8](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces) mixing tabs and spaces is disallowed. 

If you are testing using 2.x could I get you to add the `-tt` option so the code will be compatible with Python 3?

Thanks!

**Comment by tbird20d** [comment]
OK - see the latest code.  It now runs with python -tt.

I'll try to keep an eye on this and test with -tt in the future.  I added a VIM modeline to the header
of the file, so that should help keeping things consistent.
 -- Tim
