### ISSUE TITLE
setup.py ImportError: No module named setuptools

### ISSUE THREAD

**Issue by Schop0** [tbird20d/grabserial#29]
I tried to install v1.9.3 using `sudo python setup.py install` on an armhf embedded system running Debian 8 with Python 2.7.9. It could not import "setuptools". I fixed this by running `sudo apt install -y python-setuptools` first. Credits for this solution: https://stackoverflow.com/questions/14426491

**Comment by tbird20d** [comment]
Thanks for the report.  This may be helpful for others who run into the same problem.  It looks to me like this is a distribution bug, not a grabserial bug.  At least I don't see a way to work around this issue in grabserial's setup.py.  Thus, I am closing this as an issue, but will keep it in mind in case I get similar reports in the future.  Thanks again!
