### ISSUE TITLE
Coudln't open serial port

### ISSUE THREAD

**Issue by wimmatthijs** [tbird20d/grabserial#49]
So this is what happened, i think this has been an issue before?
I'm trying to log some serial data from the GPIO pins with grabserial.
I'm using a freshly downloaded raspbian image on an RPI3B+
Grabserial keeps telling me the serial ports are not found even when using the -S option.
They show up when i look in dmesg.
I couldn't wast too much time at the moment so i reverted to using this script : 
http://www.davesmotleyprojects.com/raspi/raspi-data-logger/raspi-data-logger.html
Which worked right from the getgo....
Very strange.

**Comment by tbird20d** [comment]
Sorry for the late close.  I'm not sure what the problem is.  I would have helped to know what your grabserial command line was, and what was the name of the serial device you used.  Closing as unhandled (unfortunately).
