### ISSUE TITLE
sys.stdout is flushed instead of outputfd

### ISSUE THREAD

**Issue by pieterpalmers** [tbird20d/grabserial#54]
Shouldn't outputfd be flushed instead of sys.stdout here:
https://github.com/tbird20d/grabserial/blob/a6df585f29b9385f52fbba5bf9c16470857dacb1/grabserial#L919

**Comment by tbird20d** [comment]
Absolutely.  Nice catch.  Thanks for the issue report!

**Comment by tbird20d** [comment]
fixed in commit e899ce5
