### ISSUE TITLE
-n or --nodelta not working

### ISSUE THREAD

**Issue by ditchmagnet** [tbird20d/grabserial#68]
When trying to use either -n or trying --nodelta results in:
Error parsing command line options

Command is:
grabserial -d /dev/ttyUSB0 -b 9600 -T -n

When using  the following it's fine:
grabserial -d /dev/ttyUSB0 -b 9600 -T

**Comment by ditchmagnet** [comment]
Wasn't on newest version. Disregard.

**Comment by tbird20d** [comment]
I was just going to look into this.  Even though it was apparently an old bug that was already fixed, I appreciate
that you took time to report it, and also that you took the time to update the issue when you found it was fixed.
So, thanks - and happy grabserial-ing.
 -- Tim
