### ISSUE TITLE
Is there an error log to check? (Multiple output files being created)

### ISSUE THREAD

**Issue by ditchmagnet** [tbird20d/grabserial#71]
I had this working on a different system just fine. I setup a new system and while running the same script, my output file folder keeps getting too many files created, seemingly at random. Is there a place to check why grabserial is starting new output files before the timer has finished?

Also, can I run a second instance of grabserial to monitor an additional serial cable/port?

Edit/Update:
Please disregard, my issue was in my script and I had to tweak it (strange it wasn't a problem on my other install with the same OS). Also running two instances no problem. All good here. Sorry to waste your time.

**Comment by ditchmagnet** [comment]
Issue resolved. No problem.

**Comment by tbird20d** [comment]
No problem.  Glad it's working for you.
