### ISSUE TITLE
grabserial syntax

### ISSUE THREAD

**Issue by szjozsi1** [tbird20d/grabserial#72]
Hello
I would like grabserial to display readout continuously AND save the data into file at the same time. What syntax should I use? thanks

**Comment by tbird20d** [comment]
Sorry for the slow response.  Just use '-o {filename}', and grabserial will output the data to the stdout (display) AND the file at the same time.  Data is always sent to stdout, unless -Q is used.

**Comment by szjozsi1** [comment]
hellook i did not know that (could not yet test it due to cable issues)
many many thanks!

    On Wednesday, March 1, 2023 at 01:55:02 AM GMT+1, Tim Bird ***@***.***> wrote:  
 
 


Sorry for the slow response. Just use '-o {filename}', and grabserial will output the data to the stdout (display) AND the file at the same time. Data is always sent to stdout, unless -Q is used.
